baseurl = "https://maoxunxing.com/"
title = "maoxunxing"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

canonifyurls = false
timeout = 120000

[pagination]
  pagerSize = 10
  path = "page"

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-199510588-1"

enableRobotsTXT = true

buildFuture = true

[languages]
  [languages.zh-CN]
