baseurl = "https://maoxunxing.com/"
title = "maoxunxing"
theme = "hugo-coder"
languagecode = "zh-cn"
defaultcontentlanguage = "zh-cn"
defaultContentLanguageInSubdir = "true"

paginate = 10
canonifyurls = false
timeout = 120000

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-199510588-1"

enableRobotsTXT = true

buildFuture = true

paginatePath = "page"    # 分页路径

[languages]
  [languages.zh-CN]
    weight = 2
    icon="1"
    languageName = "CN" # Name shown in the main menu
    title = "毛毛星 - 技术创新与投资复盘分享"
    description = "毛毛星(maoxunxing)的个人博客，分享前端开发、AI 应用、加密货币和指数基金投资的深度思考与实践经验"
    keywords = "毛毛星,maoxunxing,毛毛星博客,前端开发,AI应用,技术博客,加密货币,指数基金,BTC,VGT,VOO,技术创新,投资心得,felix mao"

  [languages.en]
    languageName = "EN" # Name shown in the main menu
    weight = 1
    title = "Felix Mao (maoxunxing) - Tech Innovation & Investment Insights"
    description = "Felix Mao (maoxunxing)'s blog, sharing deep insights on Frontend Development, AI Applications, Cryptocurrency and Index Fund Investment experiences"
    keywords = "maoxunxing,felix mao,tech blog,frontend development,AI applications,cryptocurrency,index funds,BTC,VGT,VOO,tech innovation,investment insights"

[markup]
  [markup.highlight]
    style = "github"
  [markup.goldmark.renderer]
    # Allow Markdown to include embedded HTML.
    unsafe= true
  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2

[languages.en.permalinks]
posts = "/:filename/"
notes = "/:filename/"
book-reports = "/:filename/"
projects = "/:filename/"
about = "/:filename/"

[languages.zh-CN.permalinks]
posts = "/:filename/"
notes = "/:filename/"
book-reports = "/:filename/"
projects = "/:filename/"
about = "/:filename/"

[social]
twitter = "maoxunxing"

[params]
    author = "Felix Mao (毛毛星)"
    info = "Tech Explorer & Investment Enthusiast | 技术探索者 & 投资爱好者"
    description = "maoxunxing (毛毛星) sharing insights on Frontend Development, AI Applications, and Investment strategies in BTC, VGT & VOO"
    keywords = "maoxunxing,毛毛星,felix mao,frontend,AI,cryptocurrency,index funds,tech blog,investment blog,BTC,VGT,VOO"
    avatarurl = "images/avatar.avif"

    favicon_32 = "/images/favicon/favicon-32x32.png"
    favicon_16 = "/images/favicon/favicon-16x16.png"

    hidecredits = false
    hidecopyright = false

    rtl = false

    custom_css = ["css/main.css"]

    photoWidths = [300, 600, 800, 1200]

    colorscheme = "auto"
    hideColorSchemeToggle = false

    #talkyardServerUrl = "https://comments-for-mtlynch-io.talkyard.net"
    #talkyardScriptUrl = "https://c1.ty-cdn.net/-/talkyard-comments.min.js"

    # 添加 notes 部分的特定分页设置
    [params.notes]
        paginate = 100

[imaging]
quality = 90
resampleFilter = "Lanczos"

# Social links
 [[params.social]]
     name = "Github"
     icon = "fab fa-github fa-2x"
     weight = 1
     url = "https://github.com/XingMXTeam/"
 [[params.social]]
     name = "Twitter"
     icon = "fab fa-twitter fa-2x"
     weight = 2
     url = "https://twitter.com/maoxunxing/"
 [[params.social]]
     name = "YouTube"
     icon = "fab fa-youtube fa-2x"
     weight = 3
     url = "https://www.youtube.com/@maodi_dev"
 [[params.social]]
     name = "Substack"
     clazz = "substack"
     link = "/images/substack.svg"  # 使用 SVG 图标的路径
     weight = 4
     url = "https://maodi.substack.com/"
 [[params.social]]
   name = "Rss"
   icon = "fa fa-rss fa-2x"
   weight = 5
   url = "https://maoxunxing.com/zh-cn/index.xml"

[[languages.en.menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1
[[languages.en.menu.main]]
    name = "Tags Cloud"
    url = "/tags-cloud/"
    weight = 2
[[languages.en.menu.main]]
    name = "Book Reports"
    url = "/book-reports/"
    weight = 3
[[languages.en.menu.main]]
  name = "Notes"
  url = "/notes/"
  weight = 4
[[languages.en.menu.main]]
    name = "About"
    url = "/about/"
    weight = 5
[[languages.en.menu.main]]
    name = "Archive"
    url = "/archive/"
    weight = 6

[[languages.zh-CN.menu.main]]
  name = "博客"
  url = "/posts/"
  weight = 1
[[languages.zh-CN.menu.main]]
  name = "标签云"
  url = "/tags-cloud/"
  weight = 2
[[languages.zh-CN.menu.main]]
  name = "读书报告"
  url = "/book-reports/"
  weight = 3
[[languages.zh-CN.menu.main]]
  name = "随笔"
  url = "/notes/"
  weight = 4
[[languages.zh-CN.menu.main]]
  name = "关于"
  url = "/about/"
  weight = 5
[[languages.zh-CN.menu.main]]
    name = "归档"
    url = "/archive/"
    weight = 6
