#!/bin/bash

# Exit on first failing command.
set -e
# Echo commands to console.
set -x
# Exit on unset variable.
set -u

tests/check-trailing-whitespace
tests/lint-markdown

hugo --minify

tests/lint-html "$@"
tests/check-seo-metadata
